### ISSUE TITLE
build Framework7 website on local machine is not show example preview of svelte 

### ISSUE THREAD

**Issue by israndi** [framework7io/framework7-website#368]
hi, 
build Framework7 website on local machine is not show example preview of svelte, and i got this message :
==============================================
Starting svelte: accordion
'D:\Framework7-v5.5.1-website\public\packages\svelte\framework7-svelte.esm.js' is imported by src\pug\docs-demos\svelte\_main.js, but could not be resolved – treating it as an external dependency
'D:\Framework7-v5.5.1-website\public\packages\svelte\framework7-svelte.esm.js' is imported by src\pug\docs-demos\svelte\accordion.svelte, but could not be resolved – treating it as an external dependency
No name was provided for external module 'D:\Framework7-v5.5.1-website\public\packages\svelte\framework7-svelte.esm.js' in output.globals – guessing 'Framework7Svelte'
Finished svelte: accordion in 745ms
....
....
....
==============================================
how to fixed it ?
Thx

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
